### ISSUE TITLE
Game Registry

### ISSUE THREAD

**Issue by O13SC3N3** [mallrat208/UBC-Ore-Registrar#14] opened 2016-02-07 04:29 UTC
No game registry errors for these ores appear until I add UBC Ore Register. Granted other mods seem no issues. Maybe a mistake ?

http://pastebin.com/raw/9F32rH20

And I would like to see Mariculture implemented as well, Is Metallurgy Ores supported?

  # Enable UBified versions of Immersive Engineering Ores (Bauxite, Copper, Lead, Nickel, Silver). [default: true]
    B:"Immersive Engineering Support"=true

Doesn't seem to work at all with the version 0.7.12 at least, no errors pop in the console like with the pastebin.

**Comment by mallrat208** [comment] 2016-02-07 18:31
Those errors are created due to how UBC itself actually registers the ores. With how my mod is setup there's nothing I can do to fix it unfortunately.

**Comment by Zeno410** [comment] 2016-02-07 23:56
How do they need to be registered?

**Comment by O13SC3N3** [comment] 2016-02-08 00:04
I thought UBC didn't really register it but did kinda like what dense ores does, just mask the ore and gives the ore associated with it in the ore dictionary?

**Comment by Zeno410** [comment] 2016-02-08 19:59
The ores are supposed to be registered, and I cleared up some earlier intermod problems by doing so.

**Comment by mallrat208** [comment] 2016-02-08 20:18
I think the issue is caused by the colon used in the second part of the name. Forge just doesn't like it. I've not seen it actually cause any issues, but it does throw the warnings about it.

**Comment by O13SC3N3** [comment] 2016-02-15 04:06
Any fix for this planned? Or plans for the mod support like Mariculture?

**Comment by Zeno410** [comment] 2016-02-15 05:05
I don't think I can fix this. You can't change names for existing blocks. I'd have to put out an incompatible version. 

Metallurgy is supported. For other ores, check out WTFOres. It does a lot.

**Comment by O13SC3N3** [comment] 2016-04-01 04:51
@mallrat208 Upgrading to UndergroundBiomesConstructs-1.7.2-test45 broke a lot of ores, only one throws an error is AM2 Ores, and thats even with the last 2 previous ubc versions. test45 AM2 still throws an error, but now all ores added through this mod has the missing texture black/purple checker. No other error is thrown with test 45 just the textures are missing. I posted @Zeno410 as well.

AM2 Error http://pastebin.com/raw/mHw0Gbhu
Posted at  https://github.com/Mithion/ArsMagica2/issues/1461

**Comment by mallrat208** [comment] 2016-04-01 16:59
I'll take a look at this after work today

**Comment by O13SC3N3** [comment] 2016-04-02 03:01
Reverted back to UndergroundBiomesConstructs-1.7.2-0.7.jar, All ores work but; Ars Magica 2 with version AM2 1.4.0.009 and .0008, this is of course with latest UBCOreRegister version. Also noticed in my configs Draconic Evolution and ClockWorkPhase were disabled. Enabled it it thew I think the same error for both mods as well. http://pastebin.com/raw/mVhmBweZ...

However upgrading to the latest UBC versions UndergroundBiomesConstructs-1.7.2-test45.jar and
UndergroundBiomeConstructs-1.7.10-v43(alpha) it will throw the same errors for all 3 mods as before, and none for the others. However all these modded ores added through the Register are the  Missing Texture Textile. I **BOLDED** the mods in the list that I have personally tested in my private server pack with each of these versions if that will help.

Factorization
Steamcraft 2
**Biomes O Plenty
Thermal Foundation**
Flaxbeard's Steam Power
**Pam's Harvestcraft
Railcraft (Sulfur Only)**
Mekanism
**Big Reactors**
The Farlanders
**Industrial Craft 2
Applied Energistics 2
Thaumcraft 4**
Magical Crops
**Project Red
Forestry**
Blue Power
**Immersive Engineering
Ars Magica 2**
Galacticraft
**Draconic Evolution**
Electrical Age
**Clockwork Phase**
Fossils and Archaeology
Jaffas and More!
**RFTools
Tainted Magic**

Side Note I am using the Following;

Forge 1614
Java 1.8.0_77 (tested with _71, _73)
Error was prevalent in forge versions 1556 1588 and 1614 (have not tried earlier versions)

**Comment by mallrat208** [comment] 2016-04-03 17:28
So after some testing...
I loaded up a few small test instances of UBC, UBC Ores and AM2 and found a few things

One, for UndergroundBiomesConstructs-1.7.2-0.7.jar the AM2 ores generated properly and existed in world with their appropriate UBC Textures and when broken dropped the proper items. The console did throw the registry error however everything worked.

Two, from what I can tell the only way to remove the registry error is to not use the UBAPIHook and instead make my own blocks, like WTFOres does. This would remove the console spam but brings up the issue of changing blocks in an existing world. There is a onMissingMappings event, I am not familiar with it however, so I'd need to do some research (Break test worlds) on it before I'm confident I can fix that.

Three, as of around October UBC now has native support for a few mods. Thermal Foundation, Thaumcraft (Cinnibar and Amber only), Mekanism (Copper and Tin Only, no Osmium), Project Red Gemstones, Biomes O Plenty Gemstones, and Enviromine Flammable Coal. From what I can tell this is for the newer test versions only.

**Comment by Zeno410** [comment] 2016-04-05 14:58
I'll look at the fixes I put in for a registry error - maybe I knocked out the AM ores fixing it

**Comment by mallrat208** [comment] 2016-05-20 06:40
@Zeno410 I figured out why those ore blocks suddenly lost their textures after the update. It looks like the current version of UBC is registering the blocks and using their localized name as the overlay texture. At no point am I sending the localized name over, so I'm not quite sure why.

Well, it may be doing that and something else. I'm currently attempting to verify the overlay texture used when registering an ore via your api. Minecraft complains about a missiing texture in the minecraft domain that should be at "textures\blocks\null LocalizedName.png"

**Comment by mallrat208** [comment] 2016-05-22 06:48
Alright, I'm going to go ahead and close this out as I can't do anything about the registry console spam and now that the ores are showing up textured with version test46

**Closed as completed by mallrat208** 2016-05-22 06:48 UTC

**Comment by Zeno410** [comment] 2016-05-22 16:40
You might want to leave this open. Just as a heads up, to stop the registry spam, I stopped some registrations which I thought I didn't really need, and that _did_ stop the registry spam, but also apparently set off the missing textures. So recently I put most of them back and now we have the spam and the textures again. So it's possibly an addressable issue, but it's a very low priority for me compared to version updates and fixing problems which actually cause gameplay trouble and not just a few hundred lines of spam in rarely-read logs.
